name: Test Docker Image

on:
  push:
    branches:
      - 'release/*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: rvnk
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: rvnk/dawn:test
